# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bbadc0dc44320b547cc18747fe0a17696bf62151271cfdff96a963bfe9258632958a8f74078c8fca02dad8c2630a7fa35b38895cb4e45e08813ab2f51fc574

test:
  secret_key_base: 31cbc64bdfb6ae881a3e983dc58879db910b0ff9325f793316cfd9fd48371d0f492eda227ae4a48f94d742b3aa0cb8c0d8a0390dc3dfde15f8a777b30734bfd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
